// This file is part of dpdk. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/dpdk/master/COPYRIGHT. No part of dpdk, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2016 The developers of dpdk. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/dpdk/master/COPYRIGHT.


#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum rte_tm_error_type
{
	RTE_TM_ERROR_TYPE_NONE = 0,
	RTE_TM_ERROR_TYPE_UNSPECIFIED = 1,
	RTE_TM_ERROR_TYPE_CAPABILITIES = 2,
	RTE_TM_ERROR_TYPE_LEVEL_ID = 3,
	RTE_TM_ERROR_TYPE_WRED_PROFILE = 4,
	RTE_TM_ERROR_TYPE_WRED_PROFILE_GREEN = 5,
	RTE_TM_ERROR_TYPE_WRED_PROFILE_YELLOW = 6,
	RTE_TM_ERROR_TYPE_WRED_PROFILE_RED = 7,
	RTE_TM_ERROR_TYPE_WRED_PROFILE_ID = 8,
	RTE_TM_ERROR_TYPE_SHARED_WRED_CONTEXT_ID = 9,
	RTE_TM_ERROR_TYPE_SHAPER_PROFILE = 10,
	RTE_TM_ERROR_TYPE_SHAPER_PROFILE_COMMITTED_RATE = 11,
	RTE_TM_ERROR_TYPE_SHAPER_PROFILE_COMMITTED_SIZE = 12,
	RTE_TM_ERROR_TYPE_SHAPER_PROFILE_PEAK_RATE = 13,
	RTE_TM_ERROR_TYPE_SHAPER_PROFILE_PEAK_SIZE = 14,
	RTE_TM_ERROR_TYPE_SHAPER_PROFILE_PKT_ADJUST_LEN = 15,
	RTE_TM_ERROR_TYPE_SHAPER_PROFILE_ID = 16,
	RTE_TM_ERROR_TYPE_SHARED_SHAPER_ID = 17,
	RTE_TM_ERROR_TYPE_NODE_PARENT_NODE_ID = 18,
	RTE_TM_ERROR_TYPE_NODE_PRIORITY = 19,
	RTE_TM_ERROR_TYPE_NODE_WEIGHT = 20,
	RTE_TM_ERROR_TYPE_NODE_PARAMS = 21,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_SHAPER_PROFILE_ID = 22,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_SHARED_SHAPER_ID = 23,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_N_SHARED_SHAPERS = 24,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_WFQ_WEIGHT_MODE = 25,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_N_SP_PRIORITIES = 26,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_CMAN = 27,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_WRED_PROFILE_ID = 28,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_SHARED_WRED_CONTEXT_ID = 29,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_N_SHARED_WRED_CONTEXTS = 30,
	RTE_TM_ERROR_TYPE_NODE_PARAMS_STATS = 31,
	RTE_TM_ERROR_TYPE_NODE_ID = 32,
}
